"""
PulseX Sri Lanka - Interactive Dashboard
Connected to Real Pipeline Data (News, Social, Weather, Econ)
"""

import streamlit as st
import pandas as pd
import json
import sys
from pathlib import Path
from datetime import datetime

# Add src to path
sys.path.append(str(Path(__file__).parent.parent))
from config import PROCESSED_DATA_DIR

st.set_page_config(page_title="PulseX Sri Lanka", layout="wide", page_icon="🇱🇰")

# Custom CSS for cards and badges
st.markdown("""
<style>
    .metric-card { 
        background: white; 
        padding: 1rem; 
        border-radius: 8px; 
        border-left: 4px solid #3B82F6; 
        box-shadow: 0 2px 4px rgba(0,0,0,0.1); 
        margin-bottom: 10px;
    }
    .risk-high { border-left-color: #EF4444 !important; }
    .source-badge {
        font-size: 0.8em;
        padding: 2px 6px;
        border-radius: 4px;
        background-color: #e5e7eb;
        color: #374151;
        font-weight: 600;
    }
</style>
""", unsafe_allow_html=True)

def load_real_data():
    """Load the JSON file generated by main.py"""
    data_path = PROCESSED_DATA_DIR / "dashboard_data.json"
    if not data_path.exists():
        st.error("⚠️ No data found. Please run 'python src/main.py' to generate insights.")
        return None
    
    with open(data_path, 'r') as f:
        return json.load(f)

def render_context_section(data):
    """Render Weather and Economic Context"""
    if 'context' not in data: 
        return

    ctx = data['context']
    
    st.markdown("### 🇱🇰 Environmental Context")
    
    # Create a container for context metrics
    with st.container():
        c1, c2, c3 = st.columns([1, 2, 1])
        
        with c1:
            # Weather Risk Score
            w_score = ctx.get('weather_risk_score', 0)
            st.metric(
                "Weather Risk", 
                f"{w_score:.2f}/1.0",
                delta="High Risk" if w_score > 0.6 else "Normal",
                delta_color="inverse"
            )
            
        with c2:
            # Weather Summary Text
            summary = ctx.get('weather_summary', 'No Weather Data')
            # Clean up the summary for display if it's too long
            short_summary = summary.split('\n')[0] if summary else "No Alerts"
            st.info(f"**Forecast:** {short_summary}")
            
        with c3:
            # Economic Data
            inflation = ctx.get('inflation_rate', 0)
            st.metric(
                "Inflation Rate", 
                f"{inflation}%", 
                delta="Yearly"
            )

    st.markdown("---")

def main():
    st.title("🇱🇰 PulseX Sri Lanka")
    st.caption(f"Real-Time Business Intelligence | Last Updated: {datetime.now().strftime('%H:%M:%S')}")
    
    data = load_real_data()
    if not data:
        return

    # --- SECTION 1: CONTEXT (Weather & Econ) ---
    render_context_section(data)

    # --- SECTION 2: KEY METRICS ---
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric("Overall Risk", f"{data['overall_risk']:.0%}", 
                 delta="Critical" if data['overall_risk'] > 0.7 else "Stable",
                 delta_color="inverse")
    with col2:
        st.metric("Public Sentiment", f"{data['sentiment_avg']:.2f}",
                 help="Scale: -1 (Negative) to +1 (Positive)")
    with col3:
        # Show breakdown of data sources
        breakdown = data.get('data_breakdown', {'news_count': 0, 'social_count': 0})
        total = breakdown['news_count'] + breakdown['social_count']
        st.metric("Data Points", total,
                 delta=f"{breakdown['social_count']} Social / {breakdown['news_count']} News",
                 delta_color="off")
    with col4:
        # Active alerts count logic (simple threshold)
        active_alerts = data.get('active_alerts', 0)
        st.metric("Active Alerts", active_alerts)

    st.markdown("---")

    # --- SECTION 3: MAIN CONTENT SPLIT ---
    col_news, col_intel = st.columns([2, 1])
    
    # LEFT COLUMN: Unified Feed
    with col_news:
        st.subheader("📡 Live Intelligence Feed")
        
        recent_items = data.get('recent_news', [])
        if recent_items:
            for item in recent_items:
                # Determine Icon and Badge based on type and sentiment
                sentiment_score = item.get('sentiment_score', 0)
                is_negative = sentiment_score < -0.2
                is_social = item.get('type') == 'social'
                
                icon = "🔴" if is_negative else "🟢"
                border_class = "risk-high" if is_negative else ""
                source_label = "🐦 Social" if is_social else "📰 News"
                
                # Render Card
                st.markdown(f"""
                <div class="metric-card {border_class}">
                    <div style="display:flex; justify-content:space-between;">
                        <span class="source-badge">{source_label}</span>
                        <small>{item.get('published_date', '')[:16]}</small>
                    </div>
                    <div style="margin-top:5px;">
                        <b>{icon} {item['title']}</b>
                    </div>
                    <div style="font-size:0.9em; color:#666; margin-top:5px;">
                        {item['source']} • Sentiment: {sentiment_score:.2f}
                    </div>
                </div>
                """, unsafe_allow_html=True)
        else:
            st.info("No recent data available.")

    # RIGHT COLUMN: AI & Risk Breakdown
    with col_intel:
        st.subheader("🤖 AI Recommendations")
        recs = data.get('recommendations', [])
        if recs:
            for rec in recs:
                st.warning(f"👉 {rec}")
        else:
            st.success("✅ No immediate actions required.")
            
        st.markdown("### 📊 Risk Breakdown")
        breakdown = data.get('risk_breakdown', {})
        for key, val in breakdown.items():
            # Format label (e.g., "sentiment_volatility" -> "Sentiment Volatility")
            label = key.replace('_', ' ').title()
            st.progress(val, text=f"{label}: {val:.0%}")
            
            # Add a small caption explaining high risks
            if val > 0.7:
                st.caption(f"⚠️ High {label} detected")

if __name__ == "__main__":
    main()
