"""
PulseX Sri Lanka - Interactive Dashboard
Connected to Real Pipeline Data
"""

import streamlit as st
import pandas as pd
import json
import sys
from pathlib import Path
from datetime import datetime

# Add src to path
sys.path.append(str(Path(__file__).parent.parent))
from config import PROCESSED_DATA_DIR

st.set_page_config(page_title="PulseX Sri Lanka", layout="wide")

# CSS (Keep your existing CSS here)
st.markdown("""
<style>
    .metric-card { background: white; padding: 1rem; border-radius: 8px; border-left: 4px solid #3B82F6; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .risk-high { border-left-color: #EF4444 !important; }
</style>
""", unsafe_allow_html=True)

def load_real_data():
    """Load the JSON file generated by main.py"""
    data_path = PROCESSED_DATA_DIR / "dashboard_data.json"
    if not data_path.exists():
        st.error("No data found. Please run 'python src/main.py' first.")
        return None
    
    with open(data_path, 'r') as f:
        return json.load(f)

def main():
    st.title("🇱🇰 PulseX Sri Lanka")
    st.markdown("Real-Time Business Intelligence & Situational Awareness")
    
    data = load_real_data()
    if not data:
        return

    # 1. Key Metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Overall Risk", f"{data['overall_risk']:.0%}", 
                 delta="High" if data['overall_risk'] > 0.6 else "Stable",
                 delta_color="inverse")
    with col2:
        st.metric("Public Sentiment", f"{data['sentiment_avg']:.2f}")
    with col3:
        st.metric("Active Alerts", data['active_alerts'])
    with col4:
        st.metric("Articles Analyzed", data['total_articles'])

    st.markdown("---")

    # 2. Recommendations & News
    col_rec, col_news = st.columns([1, 2])
    
    with col_rec:
        st.subheader("🤖 AI Recommendations")
        for rec in data['recommendations']:
            st.info(f"👉 {rec}")
            
        st.subheader("Risk Factors")
        breakdown = data.get('risk_breakdown', {})
        for key, val in breakdown.items():
            st.progress(val, text=f"{key.replace('_', ' ').title()}")

    with col_news:
        st.subheader("📰 Live News Feed")
        news_df = pd.DataFrame(data['recent_news'])
        if not news_df.empty:
            for _, row in news_df.iterrows():
                sentiment_icon = "🔴" if row.get('sentiment_score', 0) < -0.2 else "🟢"
                with st.container():
                    st.markdown(f"""
                    <div class="metric-card">
                        <b>{sentiment_icon} {row['title']}</b><br>
                        <small>{row['source']} • {row['published_date']}</small>
                    </div>
                    """, unsafe_allow_html=True)
                    st.markdown("<br>", unsafe_allow_html=True)

if __name__ == "__main__":
    main()
